name: Lint Jira Tickets

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  # we need write permission to edit the PR
  pull-requests: write
  contents: read

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR based on attached Jira ticket
        uses: TykTechnologies/jira-linter@main
        with:
          jira-base-url: https://tyktech.atlassian.net/
          jira-user-email: ${{ secrets.JIRA_EMAIL }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
