name: Lint Jira Tickets

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  # we need write permission to edit the PR
  pull-requests: write
  contents: read

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR based on attached Jira ticket
        uses: TykTechnologies/jira-linter@v0.0.4
        with:
          jira-base-url: https://tyktech.atlassian.net/
          jira-api-token: ${{ secrets.JIRA_TOKEN }}
